const OUTLINE_THICKNESS = 4;
const SLANT_LINE_THICKNESS = 2;
const SLANT_LINE_LENGTH = 16;
const SPACING_CONSTANT = 12;
const FRONT_TOP_LEFT_CORNER = { x: OUTLINE_THICKNESS / 2, y:  OUTLINE_THICKNESS / 2 };
const FRONT_TOP_RIGHT_CORNER = { x: OUTLINE_THICKNESS / 2 + WIDTH, y: OUTLINE_THICKNESS / 2 };
const FRONT_BOTTOM_RIGHT_CORNER = { x: OUTLINE_THICKNESS / 2 + WIDTH, y: OUTLINE_THICKNESS / 2 + HEIGHT };
const FRONT_BOTTOM_LEFT_CORNER = { x: OUTLINE_THICKNESS / 2, y: OUTLINE_THICKNESS / 2 + HEIGHT };
const FRONT_TOP_RIGHT_ARC_CORNER = { x: FRONT_TOP_RIGHT_CORNER.x - CORNER_RADIUS + (Math.cos(Math.PI / 4) * CORNER_RADIUS), y: FRONT_TOP_RIGHT_CORNER.y + CORNER_RADIUS - (Math.sin(Math.PI / 4) * CORNER_RADIUS) };
const FRONT_BOTTOM_RIGHT_ARC_CORNER = { x: FRONT_BOTTOM_RIGHT_CORNER.x - CORNER_RADIUS + (Math.cos(Math.PI / 4) * CORNER_RADIUS), y: FRONT_BOTTOM_RIGHT_CORNER.y - CORNER_RADIUS + (Math.sin(Math.PI / 4) * CORNER_RADIUS) };
const FRONT_BOTTOM_LEFT_ARC_CORNER = { x: FRONT_BOTTOM_LEFT_CORNER.x + CORNER_RADIUS - (Math.cos(Math.PI / 4) * CORNER_RADIUS), y: FRONT_BOTTOM_LEFT_CORNER.y - CORNER_RADIUS + (Math.sin(Math.PI / 4) * CORNER_RADIUS) };

const buttonValues = {
    frontLayer: {
        TOP_LEFT_CORNER: FRONT_TOP_LEFT_CORNER,
        TOP_RIGHT_CORNER: FRONT_TOP_RIGHT_CORNER,
        BOTTOM_RIGHT_CORNER: FRONT_BOTTOM_RIGHT_CORNER,
        BOTTOM_LEFT_CORNER: FRONT_BOTTOM_LEFT_CORNER,
        TOP_RIGHT_ARC_CORNER: FRONT_TOP_RIGHT_ARC_CORNER,
        BOTTOM_RIGHT_ARC_CORNER: FRONT_BOTTOM_RIGHT_ARC_CORNER,
        BOTTOM_LEFT_ARC_CORNER: FRONT_BOTTOM_LEFT_ARC_CORNER
    },
    intermediateLayer: {
        SLANT_LINE_LENGTH
    },
    backgroundLayer: {
        TOP_RIGHT_CORNER: {
            x: FRONT_TOP_RIGHT_CORNER.x + SLANT_LINE_LENGTH,
            y: FRONT_TOP_RIGHT_CORNER.y + SLANT_LINE_LENGTH
        },
        BOTTOM_RIGHT_CORNER: {
            x: FRONT_BOTTOM_RIGHT_CORNER.x + SLANT_LINE_LENGTH,
            y: FRONT_BOTTOM_RIGHT_CORNER.y + SLANT_LINE_LENGTH
        },
        BOTTOM_LEFT_CORNER: {
            x: FRONT_BOTTOM_LEFT_CORNER.x + SLANT_LINE_LENGTH,
            y: FRONT_BOTTOM_LEFT_CORNER.y + SLANT_LINE_LENGTH
        },
        TOP_LEFT_CORNER: {
            x: FRONT_TOP_LEFT_CORNER.x + SLANT_LINE_LENGTH,
            y: FRONT_TOP_LEFT_CORNER.y + SLANT_LINE_LENGTH
        }
    }
};

const PRESSED_SLANT_LINE_LENGTH = 8;
const PRESSED_FRONT_START_X = FRONT_TOP_LEFT_CORNER.x + SLANT_LINE_LENGTH - PRESSED_SLANT_LINE_LENGTH;
const PRESSED_FRONT_START_Y = FRONT_TOP_LEFT_CORNER.y + SLANT_LINE_LENGTH - PRESSED_SLANT_LINE_LENGTH;
const PRESSED_FRONT_TOP_LEFT_CORNER = { x: PRESSED_FRONT_START_X, y: PRESSED_FRONT_START_Y };
const PRESSED_FRONT_TOP_RIGHT_CORNER = { x: PRESSED_FRONT_START_X + WIDTH, y: PRESSED_FRONT_START_Y };
const PRESSED_FRONT_BOTTOM_RIGHT_CORNER = { x: PRESSED_FRONT_START_X + WIDTH, y: PRESSED_FRONT_START_Y + HEIGHT };
const PRESSED_FRONT_BOTTOM_LEFT_CORNER = { x: PRESSED_FRONT_START_X, y: PRESSED_FRONT_START_Y + HEIGHT };
const PRESSED_FRONT_TOP_RIGHT_ARC_CORNER = { x: PRESSED_FRONT_TOP_RIGHT_CORNER.x - CORNER_RADIUS + (Math.cos(Math.PI / 4) * CORNER_RADIUS), y: PRESSED_FRONT_TOP_RIGHT_CORNER.y + CORNER_RADIUS - (Math.sin(Math.PI / 4) * CORNER_RADIUS) };
const PRESSED_FRONT_BOTTOM_RIGHT_ARC_CORNER = { x: PRESSED_FRONT_BOTTOM_RIGHT_CORNER.x - CORNER_RADIUS + (Math.cos(Math.PI / 4) * CORNER_RADIUS), y: PRESSED_FRONT_BOTTOM_RIGHT_CORNER.y - CORNER_RADIUS + (Math.sin(Math.PI / 4) * CORNER_RADIUS) };
const PRESSED_FRONT_BOTTOM_LEFT_ARC_CORNER = { x: PRESSED_FRONT_BOTTOM_LEFT_CORNER.x + CORNER_RADIUS - (Math.cos(Math.PI / 4) * CORNER_RADIUS), y: PRESSED_FRONT_BOTTOM_LEFT_CORNER.y - CORNER_RADIUS + (Math.sin(Math.PI / 4) * CORNER_RADIUS) };

const pressedButtonValues = {
    frontLayer: {
        TOP_LEFT_CORNER: PRESSED_FRONT_TOP_LEFT_CORNER,
        TOP_RIGHT_CORNER: PRESSED_FRONT_TOP_RIGHT_CORNER,
        BOTTOM_RIGHT_CORNER: PRESSED_FRONT_BOTTOM_RIGHT_CORNER,
        BOTTOM_LEFT_CORNER: PRESSED_FRONT_BOTTOM_LEFT_CORNER,
        TOP_RIGHT_ARC_CORNER: PRESSED_FRONT_TOP_RIGHT_ARC_CORNER,
        BOTTOM_RIGHT_ARC_CORNER: PRESSED_FRONT_BOTTOM_RIGHT_ARC_CORNER,
        BOTTOM_LEFT_ARC_CORNER: PRESSED_FRONT_BOTTOM_LEFT_ARC_CORNER
    },
    intermediateLayer: {
        SLANT_LINE_LENGTH: PRESSED_SLANT_LINE_LENGTH
    },
    backgroundLayer: {
        TOP_RIGHT_CORNER: {
            x: PRESSED_FRONT_TOP_RIGHT_CORNER.x + PRESSED_SLANT_LINE_LENGTH,
            y: PRESSED_FRONT_TOP_RIGHT_CORNER.y + PRESSED_SLANT_LINE_LENGTH
        },
        BOTTOM_RIGHT_CORNER: {
            x: PRESSED_FRONT_BOTTOM_RIGHT_CORNER.x + PRESSED_SLANT_LINE_LENGTH,
            y: PRESSED_FRONT_BOTTOM_RIGHT_CORNER.y + PRESSED_SLANT_LINE_LENGTH
        },
        BOTTOM_LEFT_CORNER: {
            x: PRESSED_FRONT_BOTTOM_LEFT_CORNER.x + PRESSED_SLANT_LINE_LENGTH,
            y: PRESSED_FRONT_BOTTOM_LEFT_CORNER.y + PRESSED_SLANT_LINE_LENGTH
        },
        TOP_LEFT_CORNER: {
            x: PRESSED_FRONT_TOP_LEFT_CORNER.x + PRESSED_SLANT_LINE_LENGTH,
            y: PRESSED_FRONT_TOP_LEFT_CORNER.y + PRESSED_SLANT_LINE_LENGTH
        }
    }
};

const EFFECT_LINE_TOP_LEFT_CORNER = { x: PRESSED_FRONT_TOP_LEFT_CORNER.x - OUTLINE_THICKNESS / 2 - 10, y: PRESSED_FRONT_TOP_LEFT_CORNER.y - OUTLINE_THICKNESS / 2 - 10 };
const EFFECT_LINE_TOP_RIGHT_CORNER = { x: PRESSED_FRONT_TOP_RIGHT_CORNER.x + OUTLINE_THICKNESS / 2 + 10, y: PRESSED_FRONT_TOP_RIGHT_CORNER.y - OUTLINE_THICKNESS / 2 - 10 };
const EFFECT_LINE_BOTTOM_LEFT_CORNER = { x: PRESSED_FRONT_BOTTOM_LEFT_CORNER.x - OUTLINE_THICKNESS / 2 - 10, y: PRESSED_FRONT_BOTTOM_LEFT_CORNER.y + OUTLINE_THICKNESS / 2 + 10 };
const EFFECT_LINE_BOTTOM_RIGHT_CORNER = { x: PRESSED_FRONT_BOTTOM_RIGHT_CORNER.x + OUTLINE_THICKNESS / 2 + 10, y: PRESSED_FRONT_BOTTOM_RIGHT_CORNER.y + OUTLINE_THICKNESS / 2 + 10 };
const EFFECT_LINE_TOP = { x: (EFFECT_LINE_TOP_RIGHT_CORNER.x - EFFECT_LINE_TOP_LEFT_CORNER.x) / 2 + EFFECT_LINE_TOP_LEFT_CORNER.x, y: EFFECT_LINE_TOP_LEFT_CORNER.y };
const EFFECT_LINE_RIGHT = { x: EFFECT_LINE_TOP_RIGHT_CORNER.x + 8, y: (EFFECT_LINE_BOTTOM_RIGHT_CORNER.y - EFFECT_LINE_TOP_RIGHT_CORNER.y) / 2 + EFFECT_LINE_TOP_RIGHT_CORNER.y };
const EFFECT_LINE_BOTTOM = { x: (EFFECT_LINE_BOTTOM_RIGHT_CORNER.x - EFFECT_LINE_BOTTOM_LEFT_CORNER.x) / 2 + EFFECT_LINE_BOTTOM_LEFT_CORNER.x, y: EFFECT_LINE_BOTTOM_LEFT_CORNER.y };
const EFFECT_LINE_LEFT = { x: EFFECT_LINE_TOP_LEFT_CORNER.x- 8, y: (EFFECT_LINE_BOTTOM_RIGHT_CORNER.y - EFFECT_LINE_TOP_LEFT_CORNER.y) / 2 + EFFECT_LINE_TOP_LEFT_CORNER.y };
const EFFECT_LINE_MAJOR_WIDTH = 18;
const EFFECT_LINE_MINOR_WIDTH = 15;